code/simplemooc/simplemooc/accounts/urls.py
from django.conf.urls import url
from simplemooc.accounts import views as accviews
from django.contrib.auth import views

urlpatterns = [
    url(r'^login/$', views.login,
        {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^register/$', accviews.register, name='register'),
    url(r'^logout/$', views.logout,
        {'next_page': 'core:home'}, name='logout'),
    url(r'^dashboard/$', accviews.dashboard, name='dashboard'),
    url(r'^edit/$', accviews.edit, name='edit'),
    url(r'^edit_password/$', accviews.edit_password, name='edit_password')
]

code/simplemooc/simplemooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings  # Import from django.conf for full settings
from django.conf.urls.static import static  # Import to define static URLs

# Define namespaces to use in .html, useful if you define same name for pages
urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^accounts/', include('simplemooc.accounts.urls', namespace='accounts')),
    url(r'^courses/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
        )

code/simplemooc/simplemooc/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, PermissionsMixin, UserManager)


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField('Username', max_length=30, unique=True)
    email = models.EmailField('E-mail', unique=True)
    first_name = models.CharField('First Name', max_length=100, blank=True)
    last_name = models.CharField('Last Name', max_length=100, blank=True)
    is_active = models.BooleanField('Is Active?', blank=True, default=True)
    is_staff = models.BooleanField('Is Staff?', blank=True, default=False)
    date_joined = models.DateTimeField('Date joined', auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.first_name or self.username

    def get_short_name(self):
        return self.first_name

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

code/simplemooc/simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):

    email = forms.EmailField(label='E-mail')

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email already in use.')
        return email


class EditAccountForm(forms.ModelForm):

    def clean_email(self):
        email = self.cleaned_data['email']
        queryset = User.objects.filter(
            email=email).exclude(pk=self.instance.pk)
        if queryset.exists():
            raise forms.ValidationError('Email already in use.')
        return email

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

code/simplemooc/simplemooc/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
# from django.conf import settings

from .forms import RegisterForm, EditAccountForm


@login_required
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    return render(request, template_name)


@login_required
def edit(request):
    template_name = 'accounts/edit.html'
    context = {}
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            form = EditAccountForm(instance=request.user)
            context['success'] = True
    else:
        form = EditAccountForm(instance=request.user)
    context['form'] = form
    return render(request, template_name, context)


@login_required
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)


def register(request):
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username,
                password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('core:home')
    else:
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)


# def logout(request):
#     template_name = 'accounts/logout.html'
#     return render(request, template_name)

code/simplemooc/simplemooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %}
            <li><a href="{% url 'accounts:dashboard' %}">My Dashboard</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <a class="pure-menu-heading">My Courses</a>
            <ul>
                <li><a href="#">Course 1</a></li>
                <li><a href="#">Course 2</a></li>
                <li class="pure-menu-heading">My Account</li>
                <li><a href="{% url 'accounts:edit' %}">Edit Account</a></li>
                <li><a href="{% url 'accounts:edit_password' %}">Edit Password</a></li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}
            <p><strong>User</strong>: {{ user }}</p>
            <p><strong>E-mail</strong>: {{ user.email }}</p>
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

code/simplemooc/simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit' %}">Edit Account</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>Data Successfully Updated</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Save Changes</button>
        </div>
    </fieldset>
</form>
{% endblock %}

code/simplemooc/simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit_password' %}">Change Password</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>Your password has been changed</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Change Password</button>
        </div>
    </fieldset>
</form>
{% endblock %}

code/simplemooc/simplemooc/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}

code/simplemooc/simplemooc/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}